# Generated by Django 2.0 on 2020-04-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ithreat',
            fields=[
                ('ithreat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('times', models.IntegerField()),
                ('attack', models.GenericIPAddressField()),
                ('cn_attack_area', models.CharField(max_length=128)),
                ('en_attack_area', models.CharField(max_length=128)),
                ('victim', models.GenericIPAddressField()),
                ('cn_victim_area', models.CharField(max_length=128)),
                ('en_victim_area', models.CharField(max_length=128)),
                ('attackMT', models.DateTimeField()),
                ('last_attackMT', models.DateTimeField()),
            ],
        ),
    ]
