# Generated by Django 2.0 on 2020-03-26 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landns',
            fields=[
                ('ldnsid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.User')),
            ],
        ),
    ]
