# Generated by Django 2.0 on 2020-03-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('landns', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Landns',
            new_name='Ldns',
        ),
    ]
