# Generated by Django 2.0 on 2020-03-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landns', '0002_auto_20200326_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldns',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.User'),
        ),
    ]
