# Generated by Django 2.0 on 2020-03-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landns', '0003_auto_20200326_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldns',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ldns', to='authorization.User'),
        ),
    ]
